import './style.css';

const app = document.querySelector('#app');
const csvInput = document.querySelector('#csv-input');
const imageInput = document.querySelector('#image-input');
const restoreInput = document.querySelector('#restore-input');
const fields = ['Registration','Airline','ICAO4','Status','Registered Date','Livery','Livery Name'];
const sample = [
 ['JA801A','ANA','B788','Active','2015-07-01','Current','ANA Future Promise'], ['JA805A','ANA','B788','Active','2016-03-01','Current',''], ['JA607A','ANA','B763','Active','2003-10-01','Current',''], ['JA899A','ANA','B77W','Active','2014-03-01','Current',''], ['JA01XJ','JAL','A359','Active','2019-06-01','Current',''], ['JA02XJ','JAL','A359','Active','2019-08-01','Current',''], ['JA850A','JAL','B788','Active','2016-03-01','Current',''], ['JA81AN','ADO','B738','Active','2018-02-01','Current',''], ['JA11HC','FDA','E170','Active','2014-02-01','Past','Red'], ['JA01HC','IBX','CRJ7','Active','2007-09-01','Current','']
].map(r => Object.fromEntries(fields.map((f,i)=>[f,r[i]])));
let db = JSON.parse(localStorage.getItem('spotter-log-v1') || 'null') || { master: sample, user: {} };
let state = { view:'airlines', airline:null, icao:null, query:'', filter:'all', sort:'Registration', menu:false, selected:null, modal:null };
const save = () => localStorage.setItem('spotter-log-v1', JSON.stringify(db));
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const userOf = p => db.user[p.Registration] || {};
const spotted = p => { const u=userOf(p); return !!(u.Spotted || u.Photo); };
const pct = (a,b) => b ? Math.round(a/b*100) : 0;
const aggregate = list => ({ total:list.length, got:list.filter(spotted).length });
const sortPlanes = a => [...a].sort((x,y)=>String(x[state.sort]||'').localeCompare(String(y[state.sort]||'')));
function matches(p) { const q=state.query.toLowerCase(); const u=userOf(p); if(q && ![...fields,p.Registration].some(k=>String(p[k]||'').toLowerCase().includes(q))) return false; if(state.filter==='spotted'&&!spotted(p))return false; if(state.filter==='unspotted'&&spotted(p))return false; if(state.filter==='active'&&p.Status!=='Active')return false; if(state.filter==='current'&&p.Livery!=='Current')return false; return true; }
function header(title, sub='航空機コレクション') { return `<header class="top"><div><h1>${title}</h1><p class="subtitle">${sub}</p></div><button class="icon-btn" data-action="menu" aria-label="メニュー">☰</button></header>${state.menu?`<nav class="menu"><button data-action="import">CSVをインポート</button><button data-action="export-csv">CSVをエクスポート</button><button data-action="backup">JSONバックアップ</button><button data-action="restore">JSONを復元</button></nav>`:''}`; }
function controls() { return `<div class="toolbar"><input class="search" data-role="search" value="${esc(state.query)}" placeholder="レジ・航空会社・機種を検索"/><select data-role="sort"><option>Registration</option><option>Airline</option><option>ICAO4</option><option>Registered Date</option></select></div><div class="filters">${[['all','すべて'],['spotted','撮影済み'],['unspotted','未撮影'],['active','Active'],['current','⭐ Current']].map(([v,l])=>`<button class="chip ${state.filter===v?'active':''}" data-filter="${v}">${l}</button>`).join('')}</div>`; }
function progress(g) { return `<div class="progress"><i style="width:${pct(g.got,g.total)}%"></i></div><span class="count">${g.got} / ${g.total}</span><span class="percent">${pct(g.got,g.total)}%</span>`; }
function airlines() { const filtered=db.master.filter(matches); const groups=Object.groupBy(filtered,p=>p.Airline||'未分類'); const total=aggregate(db.master); return `${header('Spotter Log')}<section class="summary"><div><strong>${total.got}</strong><span>COLLECTED</span></div><div><strong>${total.total}</strong><span>AIRCRAFT</span></div><div><strong>${pct(total.got,total.total)}%</strong><span>COMPLETE</span></div></section>${controls()}<h2>航空会社</h2><main class="grid">${Object.entries(groups).sort().map(([name,list])=>{const g=aggregate(list);return `<button class="card" data-airline="${esc(name)}"><div class="card-head"><span class="title">${esc(name)}</span><span class="muted">${list.length}機</span></div>${progress(g)}</button>`}).join('') || '<div class="empty">該当する機体がありません</div>'}</main>`; }
function types() { const planes=db.master.filter(p=>p.Airline===state.airline&&matches(p)); const groups=Object.groupBy(planes,p=>p.ICAO4||'未分類'); return `${header('‹ '+esc(state.airline),'機種を選択')}<button class="back" data-action="back">← 航空会社</button><div style="height:14px"></div>${controls()}<main class="grid">${Object.entries(groups).sort().map(([type,list])=>`<button class="card" data-icao="${esc(type)}"><div class="card-head"><span class="title">${esc(type)}</span>${list.some(p=>p.Livery==='Current')?'<span class="star">★</span>':''}</div>${progress(aggregate(list))}</button>`).join('') || '<div class="empty">該当する機体がありません</div>'}</main>`; }
function planes() { const list=sortPlanes(db.master.filter(p=>p.Airline===state.airline&&p.ICAO4===state.icao&&matches(p))); return `${header('‹ '+esc(state.icao),esc(state.airline)+' · 機体一覧')}<button class="back" data-action="back">← 機種一覧</button><div style="height:14px"></div>${controls()}<main class="plane-list">${list.map(p=>{const u=userOf(p);return `<article class="plane" data-plane="${esc(p.Registration)}"><div class="thumb ${u.Photo?'':'placeholder'}">${u.Photo?`<img class="thumb" src="${u.Photo}" alt="${esc(p.Registration)}"/>`:'✈'}</div><div><div class="reg">${esc(p.Registration)} ${p.Livery==='Current'?'<span class="star">★</span>':''}</div><div class="muted">${esc(p.Airline)} · ${esc(p.ICAO4)}</div><div class="muted">${esc(p.Status)}</div></div>${spotted(p)?'<span class="tag">SPOTTED</span>':'<span class="muted">未撮影</span>'}</article>`}).join('') || '<div class="empty">該当する機体がありません</div>'}</main>`; }
function detail() { const p=state.selected, u=userOf(p); const all=[...fields,['Airport',u.Airport||''],['Date Taken',u['Date Taken']||'']]; return `${header('機体詳細',p.Registration)}<button class="back" data-action="back">← 機体一覧</button><div style="height:14px"></div><article class="detail">${u.Photo?`<img class="hero" src="${u.Photo}" alt="${esc(p.Registration)}"/>`:'<div class="hero placeholder">✈</div>'}<div class="detail-body"><div class="card-head"><div><div class="title">${esc(p.Registration)}</div><div class="muted">${esc(p.Airline)} · ${esc(p.ICAO4)}</div></div>${spotted(p)?'<span class="tag">SPOTTED</span>':'<span class="muted">未撮影</span>'}</div><div class="data">${all.map(([k,v])=>`<div class="field"><label>${k}</label><div>${esc(v||'—')}</div></div>`).join('')}</div><div class="actions"><button class="primary" data-action="edit">${spotted(p)?'撮影情報を編集':'この機体を登録'}</button>${u.Photo?'<button class="secondary" data-action="remove-photo">写真を削除</button>':''}</div></div></article>`; }
function modal() { const p=state.selected, u=userOf(p); if(!state.modal||!p)return ''; return `<div class="modal"><section class="sheet"><h2>撮影を記録 <button class="icon-btn" data-action="close">×</button></h2><form class="form" data-role="form"><label>Registration<input class="readonly" value="${esc(p.Registration)}" readonly></label><label>Airport<input name="Airport" value="${esc(u.Airport||'')}" placeholder="例: HND"></label><label>Date Taken<input name="Date Taken" type="date" value="${esc(u['Date Taken']||'')}"></label><label>代表写真 <button type="button" class="secondary" data-action="photo">${u.Photo?'写真を変更':'写真を選ぶ（3:2で自動トリミング）'}</button></label><label><input name="Spotted" type="checkbox" ${spotted(p)?'checked':''}> 写真なしで撮影済みにする</label><div class="modal-actions"><button class="secondary" type="button" data-action="close">キャンセル</button><button class="primary">保存</button></div></form></section></div>`; }
function render(){ let page=state.view==='airlines'?airlines():state.view==='types'?types():state.view==='planes'?planes():detail(); app.innerHTML=page+modal(); const s=document.querySelector('[data-role="sort"]');if(s)s.value=state.sort; }
function openPlane(reg){ state.selected=db.master.find(p=>p.Registration===reg);state.view='detail';render(); }
function csvRows(text) { const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){let c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows; }
function download(name, body, type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function crop(file){ const img=await createImageBitmap(file); const ratio=1.5;let sw=img.width,sh=img.height;if(sw/sh>ratio)sw=sh*ratio;else sh=sw/ratio;const sx=(img.width-sw)/2,sy=(img.height-sh)/2;const c=document.createElement('canvas');c.width=1200;c.height=800;c.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,1200,800);return c.toDataURL('image/jpeg',.84); }
app.addEventListener('click',e=>{const b=e.target.closest('button,[data-plane]');if(!b)return;if(b.dataset.airline){state.airline=b.dataset.airline;state.view='types'}else if(b.dataset.icao){state.icao=b.dataset.icao;state.view='planes'}else if(b.dataset.plane)openPlane(b.dataset.plane);else {const a=b.dataset.action;if(a==='menu')state.menu=!state.menu;if(a==='back'){if(state.view==='types')state.view='airlines';else if(state.view==='planes')state.view='types';else state.view='planes'}if(a==='edit')state.modal='edit';if(a==='close')state.modal=null;if(a==='photo')imageInput.click();if(a==='import')csvInput.click();if(a==='restore')restoreInput.click();if(a==='export-csv'){const lines=[fields.join(','),...db.master.map(p=>fields.map(k=>'"'+String(p[k]||'').replaceAll('"','""')+'"').join(','))];download('spotter-log-master.csv',lines.join('\n'),'text/csv')}if(a==='backup')download('spotter-log-backup.json',JSON.stringify(db,null,2),'application/json');if(a==='remove-photo'){delete db.user[state.selected.Registration].Photo;save()} }if(b.dataset.filter){state.filter=b.dataset.filter}render();});
app.addEventListener('input',e=>{if(e.target.dataset.role==='search'){state.query=e.target.value;render();document.querySelector('[data-role="search"]')?.focus();}});app.addEventListener('change',e=>{if(e.target.dataset.role==='sort'){state.sort=e.target.value;render();}});app.addEventListener('submit',e=>{if(!e.target.matches('[data-role="form"]'))return;e.preventDefault();const f=new FormData(e.target),u=db.user[state.selected.Registration]||{};u.Airport=f.get('Airport');u['Date Taken']=f.get('Date Taken');u.Spotted=!!f.get('Spotted')||!!u.Photo;db.user[state.selected.Registration]=u;save();state.modal=null;render();});
csvInput.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;const rows=csvRows(await file.text());const h=rows.shift()?.map(x=>x.trim());if(!h||!h.includes('Registration'))return alert('Registration列を含むCSVを選択してください。');db.master=rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]?.trim()||'']))).filter(p=>p.Registration);save();state={...state,view:'airlines',query:'',menu:false};render();e.target.value='';});
imageInput.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const u=db.user[state.selected.Registration]||{};u.Photo=await crop(f);u.Spotted=true;db.user[state.selected.Registration]=u;save();render()}catch{alert('画像を読み込めませんでした。')}e.target.value='';});
restoreInput.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.master))throw Error();db=x;save();state={...state,view:'airlines',menu:false};render()}catch{alert('Spotter LogのバックアップJSONを選択してください。')}e.target.value='';});
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');render();
